CREATE TABLE IF NOT EXISTS airlines(
   id        INTEGER  NOT NULL PRIMARY KEY AUTO_INCREMENT
  ,name      VARCHAR(255) NOT NULL
  ,iata_code VARCHAR(3)
  ,icao_code VARCHAR(4)
);
REPLACE INTO airlines(name,iata_code,icao_code) VALUES
 ('1Time Airline','1T','RNX')
,('40-Mile Air','Q5','MLA')
,('Ansett Australia','AN','AAA')
,('Abacus International','1B',NULL)
,('Aigle Azur','ZI','AAF')
,('Aloha Airlines','AQ','AAH')
,('American Airlines','AA','AAL')
,('Asiana Airlines','OZ','AAR')
,('Askari Aviation','4K','AAS')
,('Afriqiyah Airways','8U','AAW')
,('Allegiant Air','G4','AAY')
,('ABSA - Aerolinhas Brasileiras','M3','TUS')
,('Astral Aviation','8V','ACP')
,('Air Tindi','8T',NULL)
,('Ada Air','ZY','ADE')
,('Adria Airways','JP','ADR')
,('Air Europa','UX','AEA')
,('Aero Benin','EM','AEB')
,('Aegean Airlines','A3','AEE')
,('Air Europe','PE','AEL')
,('Alaska Central Express','KO','AER')
,('ACES Colombia',NULL,'AES')
,('Astraeus','5W','AEU')
,('Aerosvit Airlines','VV','AEW')
,('Air Italy','I9','AEY')
,('Alliance Airlines','QQ','UTY')
,('Ariana Afghan Airlines','FG','AFG')
,('Aeroflot Russian Airlines','SU','AFL')
,('Air Bosna','JA','BON')
,('Air France','AF','AFR')
,('Air Caledonie International','SB','ACI')
,('Air Salone','2O',NULL)
,('Air Cargo Carriers','2Q','SNC')
,('Air Namibia','SW','NMB')
,('Aerolitoral','D 5.00','SLI')
,('Air Glaciers','7T','AGV')
,('Aviogenex',NULL,'AGX')
,('Aeroper','PL','PLI')
,('Atlas Blue','8A','BMM')
,('Azerbaijan Airlines','J2','AHY')
,('Avies','U3','AIA')
,('Airblue','ED','ABQ')
,('Airlift International',NULL,'AIR')
,('Air Berlin','AB','BER')
,('Air India Limited','AI','AIC')
,('Air Bourbon','ZB','BUB')
,('Air Atlanta Icelandic','CC','ABD')
,('Air Tahiti Nui','TN','THT')
,('Arkia Israel Airlines','IZ','AIZ')
,('Air Jamaica','JM','AJM')
,('Air One','AP','ADH')
,('Air Sahara','S2','RSH')
,('Air Malta','KM','AMC')
,('Air Japan','NQ','AJX')
,('Air Korea Co. Ltd.',NULL,'AKA')
,('Air Kiribati','4A','AKL')
,('America West Airlines','HP','AWE')
,('Air Wisconsin','ZW','AWI')
,('Tatarstan Airlines','U9','TAK')
,('Allegheny Commuter Airlines',NULL,'ALO')
,('Air Sunshine',NULL,'RSI')
,('Air Libert','VD',NULL)
,('Air Malawi','QM','AML')
,('Air Sicilia','BM',NULL)
,('ATA Airlines',NULL,'AMT')
,('Air Macau','NX','AMU')
,('AMC Airlines',NULL,'AMV')
,('Air Seychelles','HM','SEY')
,('AeroMéxico','AM','AMX')
,('All Nippon Airways','NH','ANA')
,('Air Nostrum','YW','ANE')
,('Air Niugini','PX','ANG')
,('Air Arabia','G9','ABY')
,('Air Canada','AC','ACA')
,('Air Baltic','BT','BTI')
,('Air Nippon','EL','ANK')
,('Airnorth','TL','ANO')
,('Air North Charter - Canada','4N','ANT')
,('Air New Zealand','NZ','ANZ')
,('Alitalia Express','XM','SMX')
,('Aero Flight','GV','ARF')
,('Arrow Air','JW','APW')
,('Aerocondor','2B','ARD')
,('Aires','4C','ARE')
,('Aerolineas Argentinas','AR','ARG')
,('Alaska Airlines','AS','ASA')
,('Air Sinai','D 4.00','ASD')
,('Atlantic Southeast Airlines','EV','ASQ')
,('Astrakhan Airlines','OB','ASZ')
,('Air Tanzania','TC','ATC')
,('Air Burkina','2J','VBW')
,('Airlines Of Tasmania','FO','ATM')
,('Air Saint Pierre','PJ','SPM')
,('Austrian Airlines','OS','AUA')
,('Air Southwest',NULL,'WOW')
,('Augsburg Airways','IQ','AUB')
,('ATUR',NULL,'TUR')
,('Abu Dhabi Amiri Flight','MO','AUH')
,('Aeroflot-Nord','5N','AUL')
,('Aurigny Air Services','GR','AUR');
REPLACE INTO airlines(name,iata_code,icao_code) VALUES
 ('Austral Lineas Aereas','AU','AUT')
,('Avianca - Aerovias Nacionales de Colombia','AV','AVA')
,('Air Vanuatu','NF','AVN')
,('Air Bangladesh','B9','BGD')
,('Air Mediterranee','DR','BIE')
,('Air Moorea',NULL,'TAH')
,('Aeroline GmbH','7E','AWU')
,('Air Wales','6G','AWW')
,('Air Caraïbes','TX','FWI')
,('Air India Express','IX','AXB')
,('Air Exel','XT','AXL')
,('AirAsia','AK','AXM')
,('Atlant-Soyuz Airlines','3G','AYZ')
,('Alitalia','AZ','AZA')
,('Amaszonas','Z8','AZN')
,('Air Zimbabwe','UM','AZW')
,('Aserca Airlines','R7','OCA')
,('Rossiya-Russian Airlines','FV','SDM')
,('American Eagle Airlines','MQ','EGF')
,('AD Aviation',NULL,'VUE')
,('Air Ivoire','VU','VUN')
,('Air Botswana','BP','BOT')
,('Air Foyle','GS','UPA')
,('Air Tahiti','VT','VTA')
,('Air VIA','VL','VIM')
,('Africa West','FK','WTA')
,('ATRAN Cargo Airlines','V8','VAS')
,('Air China','CA','CCA')
,('Aero Condor Peru','Q6','CDP')
,('Air Chathams','CV','CVA')
,('Air Marshall Islands','CW','CWM')
,('Access Air','ZA','CYD')
,('Air Algerie','AH','DAH')
,('Adam Air','KI','DHI')
,('Air Dolomiti','EN','DLA')
,('Aeroflot-Don','D 9.00','DNV')
,('Air Madrid','NM','DRD')
,('Aer Lingus','EI','EIN')
,('Air Finland','OF','FIF')
,('Airfix Aviation',NULL,'FIX')
,('Air Pacific','FJ','FJI')
,('Atlantic Airways','RC','FLI')
,('Air Florida','QH','FLZ')
,('Air Iceland','NY','FXI')
,('Air Philippines','2P','GAP')
,('Air Guinee Express','2U','GIP')
,('Air Greenland','GL','GRL')
,('Atlas Air','5Y','GTI')
,('Air Guyane','GG','GUY')
,('Air Bagan','W9','JAB')
,('Air Canada Jazz','QK','JZA')
,('Atlasjet','KK','KKK')
,('Air Koryo','JS','KOR')
,('Air Astana','KC','KZR')
,('Albanian Airlines','LV','LBC')
,('Air Alfa',NULL,'LFA')
,('Aerolane','XL','LNE')
,('Atlantis European Airways','TD','LUR')
,('Air Luxor','LK','LXR')
,('Air Mauritius','MK','MAU')
,('Air Madagascar','MD','MDG')
,('Air Moldova','9U','MLD')
,('Air Plus Comet','A7','MPD')
,('Astair','D 8.00',NULL)
,('Aero Contractors','AJ','NIG')
,('Aeropelican Air Services','OT','PEL')
,('Aer Arann','RE','REA')
,('Air Austral','UU','REU')
,('Asian Spirit','6K','RIT')
,('Air Afrique','RK','RKA')
,('Airlinair','A5','RLA')
,('Aero Lanka','QL','RLN')
,('Air Salone','20','RNE')
,('Armavia','U8','RNV')
,('AeroRep','P5','RPB')
,('Aero-Service','BF','RSR')
,('Aerosur','5L','RSU')
,('Aeronorte',NULL,'RTE')
,('Avient Aviation','Z3','SMJ')
,('Aircompany Yakutia','R3','SYL')
,('Aeromar','VW','TAO')
,('Arkefly','OR','TFL')
,('Airlines PNG','CG','TOK')
,('AirTran Airways','FL','TRS')
,('Air Transat','TS','TSC')
,('Avialeasing Aviation Company','EC','TWN')
,('Tyrolean Airways','VO','TYR')
,('Aerolineas Galapagos (Aerogal)','2K','GLG')
,('Alrosa Mirny Air Enterprise','6R','DRU')
,('British Airways','BA','BAW')
,('Biman Bangladesh Airlines','BG','BBC')
,('Belair Airlines','4T','BHP')
,('Bahamasair','UP','BHS')
,('Balkan Bulgarian Airlines','LZ',NULL)
,('British International Helicopters','BS','BIH')
,('BF-Lento OY',NULL,'BKF')
,('Bangkok Airways','PG','BKP')
,('Blue1','KF','BLF')
,('Baltic Airlines',NULL,'BLL')
,('Bearskin Lake Air Service','JV','BLS');
REPLACE INTO airlines(name,iata_code,icao_code) VALUES
 ('Bellview Airlines','B3','BLV')
,('bmi','BD','BMA')
,('bmibaby','WW','BMI')
,('Bemidji Airlines','CH','BMJ')
,('British Midland Regional',NULL,'BMR')
,('Blue Panorama Airlines','BV','BPA')
,('Budapest Aircraft Services/Manx2',NULL,'BPS')
,('Bering Air','8E','BRG')
,('Brazilian Air Force',NULL,'BRS')
,('Belavia Belarusian Airlines','B2','BRU')
,('Metro Batavia','7P','BTV')
,('Berjaya Air','J8','BVT')
,('Blue Wings','QW','BWG')
,('Brit Air','DB','BZH')
,('Brussels Airlines','SN','DAT')
,('Binter Canarias','NT','IBB')
,('Blue Air','0B','JOR')
,('British Mediterranean Airways','KJ','LAJ')
,('Bulgaria Air','FB','LZB')
,('Barents AirLink','8N','NKF')
,('CAL Cargo Air Lines','5C','ICL')
,('Calima Aviacion','XG','CLI')
,('Canadian Airlines','CP','CDN')
,('Canadian North','5T','MPE')
,('Cape Air','9K','KAP')
,('Caribbean Airlines','BW','BWA')
,('Carpatair','V3','KRP')
,('Caspian Airlines','RV','CPN')
,('Cathay Pacific','CX','CPA')
,('Cayman Airways','KX','CAY')
,('Cebu Pacific','5J','CEB')
,('Central Connect Airlines',NULL,'CCG')
,('Centralwings','C0','CLW')
,('Charter Air',NULL,'CHW')
,('Chautauqua Airlines','RP','CHQ')
,('China Airlines','CI','CAL')
,('China Eastern Airlines','MU','CES')
,('China Southern Airlines','CZ','CSN')
,('China United Airlines','HR','CUA')
,('Yunnan Airlines','3Q','CYH')
,('Cimber Air','QI','CIM')
,('Cirrus Airlines','C9','RUS')
,('City Airline','CF','SDR')
,('City Connexion Airlines','G3','CIX')
,('CityJet','WX','BCY')
,('BA CityFlyer','CJ','CFE')
,('Click Airways',NULL,'CGK')
,('Coastal Air','DQ',NULL)
,('Colgan Air','9L','CJC')
,('Comair','OH','COM')
,('Comair','MN','CAW')
,('CommutAir','C5','UCA')
,('Comores Airlines','KR','CWK')
,('Compass Airlines','CP','CPZ')
,('Condor Flugdienst','DE','CFG')
,('Consorcio Aviaxsa','6A','CHP')
,('Contact Air','C3','KIS')
,('Continental Airlines','CO','COA')
,('Continental Express','CO',NULL)
,('Continental Micronesia','CS','CMI')
,('Conviasa','V0','VCV')
,('Copa Airlines','CM','CMP')
,('Copterline',NULL,'AAQ')
,('Corendon Airlines',NULL,'CAI')
,('Corsairfly','SS','CRL')
,('Corse-Mediterranee','XK','CCM')
,('Crest Aviation',NULL,'CAN')
,('Croatia Airlines','OU','CTN')
,('Crown Airways',NULL,'CRO')
,('Cubana de Aviación','CU','CUB')
,('Cyprus Airways','CY','CYP')
,('Cyprus Turkish Airlines','YK',NULL)
,('Czech Airlines','OK','CSA')
,('DAT Danish Air Transport','DX','DTR')
,('Daallo Airlines','D 3.00','DAO')
,('Dalavia','H8','KHB')
,('Darwin Airline','D 0.00','DWT')
,('Delta Aerotaxi',NULL,'DEA')
,('Delta Air Lines','DL','DAL')
,('Denim Air',NULL,'DNM')
,('Deutsche Bahn','2A',NULL)
,('Djibouti Airlines','D 8.00','DJB')
,('Dniproavia',NULL,'UDN')
,('Dominicana de Aviaci','DO','DOA')
,('Domodedovo Airlines','E3','DMO')
,('DonbassAero','D 5.00','UDC')
,('Dragonair','KA','HDA')
,('Druk Air','KB','DRK')
,('Dubrovnik Air',NULL,'DBK')
,('Dutch Antilles Express',NULL,'DNL')
,('dba','DI','BAG')
,('EVA Air','BR','EVA')
,('Eagle Air','H7',NULL)
,('East African','QU','UGX')
,('Eastern Airways','T3','EZE')
,('Eastland Air','DK','ELA')
,('Ecuavia',NULL,'ECU')
,('Edelweiss Air','WK','EDW')
,('Egyptair','MS','MSR')
,('El Al Israel Airlines','LY','ELY');
REPLACE INTO airlines(name,iata_code,icao_code) VALUES
 ('El-Buraq Air Transport','UZ','BRQ')
,('Emirates','EK','UAE')
,('Empresa Ecuatoriana De Aviacion','EU','EEA')
,('Eritrean Airlines','B8','ERT')
,('Estonian Air','OV','ELL')
,('Ethiopian Airlines','ET','ETH')
,('Etihad Airways','EY','ETD')
,('Euro Exec Express','RZ',NULL)
,('Eurocypria Airlines','UI','ECA')
,('Eurofly Service','GJ','EEU')
,('Eurolot','K2','ELO')
,('European Air Express','EA','EAL')
,('Eurowings','EW','EWG')
,('Evergreen International Airlines','EZ','EIA')
,('Excel Airways','JN','XLA')
,('Excel Charter',NULL,'XEL')
,('Express One International','EO','LHN')
,('ExpressJet','XE','BTA')
,('easyJet','U2','EZY')
,('Far Eastern Air Transport','EF','EFA')
,('Finnair','AY','FIN')
,('Finncomm Airlines','FC','WBA')
,('Firefly','FY','FFM')
,('First Air','7F','FAB')
,('First Choice Airways','DP','FCA')
,('Flightline','B5','FLT')
,('Florida West International Airways','RF','FWL')
,('AirAsia X','D 7.00','XAX')
,('FlyLal','TE','LIL')
,('FlyNordic','LF','NDC')
,('Flybaboo','F7','BBO')
,('Flybe','BE','BEE')
,('Flyglobespan','B4','GSM')
,('Flyhy Cargo Airlines',NULL,'FYH')
,('Formosa Airlines','VY','FOS')
,('Freedom Air','FP','FRE')
,('Freedom Airlines',NULL,'FRL')
,('Frontier Airlines','F9','FFT')
,('Frontier Flying Service','2F','FTA')
,('GB Airways','GT','GBL')
,('Garuda Indonesia','GA','GIA')
,('Gazpromavia','4G','GZP')
,('Georgian Airways','A9','TGZ')
,('Georgian National Airlines','QB','GFG')
,('Germania','ST','GMI')
,('Germanwings','4U','GWI')
,('Ghana International Airlines','G0','GHB')
,('Go Air','G8','GOW')
,('GoJet Airlines','G7','GJS')
,('Gol Transportes Aéreos','G3','GLO')
,('Golden Air','DC','GAO')
,('Great Lakes Airlines','ZK','GLA')
,('Grupo TACA','TA','TAT')
,('Gulf Air',NULL,'GFA')
,('Gulf Air Bahrain','GF','GBA')
,('Gulfstream International Airlines',NULL,'GFT')
,('Hageland Aviation Services','H6','HAG')
,('Hainan Airlines','HU','CHH')
,('Haiti Ambassador Airlines','2T','HAM')
,('Hamburg International','4R','HHI')
,('TUIfly','X3','HLX')
,('Hapagfly','HF','HLF')
,('Hawaiian Airlines','HA','HAL')
,('Hawkair','BH',NULL)
,('Heli France','8H','HFR')
,('Helijet','JB','JBA')
,('Hellas Jet','T4','HEJ')
,('Hello','HW','FHE')
,('Helvetic Airways','2L','OAW')
,('Hex\'Air','UD','HER')
,('Highland Airways',NULL,'HWY')
,('Hokkaido International Airlines','HD','ADO')
,('Hong Kong Airlines','HX','CRK')
,('Hong Kong Express Airways','UO','HKE')
,('Horizon Air','QX','QXE')
,('Horizon Airlines','BN','HZA')
,('Iberia Airlines','IB','IBE')
,('Iberworld','TY','IWD')
,('Ibex Airlines','FW','IBX')
,('Icar Air',NULL,'RAC')
,('Icelandair','FI','ICE')
,('Imair Airlines','IK','ITX')
,('IndiGo Airlines','6E','IGO')
,('Indian Airlines','IC','IAC')
,('Indigo','I9','IBU')
,('Indonesia AirAsia','QZ','AWQ')
,('Indonesian Airlines','IO','IAA')
,('Interair South Africa','D 6.00','ILN')
,('Interavia Airlines','ZA','SUW')
,('Interlink Airlines','ID','ITK')
,('Intersky','3L','ISK')
,('Iran Air','IR','IRA')
,('Iran Aseman Airlines','EP','IRC')
,('Iraqi Airways','IA','IAW')
,('Island Airlines','IS',NULL)
,('Cargo Plus Aviation','8L','CGP')
,('Islas Airways','IF','ISW')
,('Islena De Inversiones','WC','ISV')
,('Israir','6H','ISR')
,('Itek Air','GI','IKA');
REPLACE INTO airlines(name,iata_code,icao_code) VALUES
 ('JAL Express','JC','JEX')
,('JALways','JO','JAZ')
,('Japan Airlines','JL','JAL')
,('Japan Airlines Domestic','JL','JAL')
,('Japan Asia Airways','EG','JAA')
,('Japan Transocean Air','NU','JTA')
,('Jazeera Airways','J9','JZR')
,('Jeju Air','7C','JJA')
,('Jet Airways','9W','JAI')
,('Jet Airways','QJ',NULL)
,('Jetstar Asia Airways','3K','JSA')
,('Jet2.com','LS','EXS')
,('Jet4You','8J','JFU')
,('JetBlue Airways','B6','JBU')
,('Jetairfly','JF','JAF')
,('Jetflite',NULL,'JEF')
,('Jetstar Airways','JQ','JST')
,('Juneyao Airlines','HO','DKH')
,('KD Avia','KD','KNI')
,('KLM Cityhopper','WA','KLC')
,('KLM Royal Dutch Airlines','KL','KLM')
,('Kam Air','RQ','KMF')
,('Kavminvodyavia','KV','MVD')
,('Kendell Airlines',NULL,'KDA')
,('Kenmore Air','M5','KEN')
,('Kenya Airways','KQ','KQA')
,('Kingfisher Airlines','IT','KFR')
,('Kish Air','Y9','IRK')
,('Kogalymavia Air Company','7K','KGL')
,('Korean Air','KE','KAL')
,('Kosmos',NULL,'KSM')
,('Krasnojarsky Airlines','7B','KJC')
,('Kuban Airlines','GW','KIL')
,('Kuwait Airways','KU','KAC')
,('Kuzu Airlines Cargo','GO','KZU')
,('LACSA','LR','LRC')
,('LAN Airlines','LA','LAN')
,('LAN Argentina','4M','DSM')
,('LAN Express','LU','LXP')
,('LAN Peru','LP','LPE')
,('LOT Polish Airlines','LO','LOT')
,('LTE International Airways','XO','LTE')
,('LTU Austria','L3','LTO')
,('Lao Airlines','QV','LAO')
,('LatCharter',NULL,'LTC')
,('Lauda Air','NG','LDA')
,('Leeward Islands Air Transport','LI','LIA')
,('Libyan Arab Airlines','LN','LAA')
,('Linhas A','LM','LAM')
,('Lion Mentari Airlines','JT','LNI')
,('Luftfahrtgesellschaft Walter','HE','LGW')
,('Lufthansa','LH','DLH')
,('Lufthansa Cargo','LH','GEC')
,('Lufthansa CityLine','CL','CLH')
,('Lufttransport','L5','LTR')
,('Luxair','LG','LGL')
,('L','MJ','LPR')
,('MasAir','M7','MAA')
,('MAT Macedonian Airlines','IN','MAK')
,('MIAT Mongolian Airlines','OM','MGL')
,('MNG Airlines','MB','MNB')
,('Macair Airlines','CC','MCK')
,('Maersk','DM',NULL)
,('Mahan Air','W5','IRM')
,('Malaysia Airlines','MH','MAS')
,('Malmo Aviation',NULL,'SCW')
,('Malmö Aviation','TF','SCW')
,('Malta Air Charter','R5','MAC')
,('Malév','MA','MAH')
,('Mandala Airlines','RI','MDL')
,('Mandarin Airlines','AE','MDA')
,('Mango','JE','MNO')
,('Martinair','MP','MPH')
,('Maxair','8M','MXL')
,('Maya Island Air','MW','MYD')
,('Meridiana','IG','ISS')
,('Merpati Nusantara Airlines','MZ','MNA')
,('Mesa Airlines','YV','ASH')
,('Mesaba Airlines','XJ','MES')
,('Mexicana de Aviaci','MX','MXA')
,('Middle East Airlines','ME','MEA')
,('Midway Airlines','JI','MDW')
,('Midwest Airlines','YX','MEP')
,('Midwest Airlines (Egypt)','MY','MWA')
,('Moldavian Airlines','2M','MDV')
,('Monarch Airlines','ZB','MON')
,('Myway Airlines','8I',NULL)
,('Montenegro Airlines','YM','MGX')
,('Morningstar Air Express',NULL,'MAL')
,('Moskovia Airlines','3R','GAI')
,('Motor Sich','M9','MSI')
,('MyTravel Airways','VZ','MYT')
,('Myanma Airways','UB','UBA')
,('Myanmar Airways International','8M','MMM')
,('Myflug',NULL,'MYA')
,('Nasair','UE','NAS')
,('National Jet Systems','NC','NJS')
,('Nationwide Airlines','CE','NTW')
,('Nauru Air Corporation','ON','RON')
,('Nepal Airlines','RA','RNA');
REPLACE INTO airlines(name,iata_code,icao_code) VALUES
 ('NetJets','1I','EJA')
,('New England Airlines','EJ','NEA')
,('NextJet','2N','NTJ')
,('Niki','HG','NLY')
,('Nok Air','DD','NOK')
,('Norfolk County Flight College',NULL,'NCF')
,('North American Airlines',NULL,'NTM')
,('North American Charters',NULL,'HMR')
,('Northern Dene Airways','U7',NULL)
,('Northwest Airlines','NW','NWA')
,('Northwestern Air','J3','PLR')
,('Norwegian Air Shuttle','DY','NAX')
,('Norwegian Aviation College',NULL,'TFN')
,('Nouvel Air Tunisie','BJ','LBT')
,('Novair','1I','NVR')
,('Nas Air','XY','KNE')
,('Oasis Hong Kong Airlines','O8','OHK')
,('Ocean Air',NULL,'BCN')
,('Oceanair','O6','ONE')
,('Oceanic Airlines','O2',NULL)
,('Olympic Airlines','OA','OAL')
,('Oman Air','WY','OMA')
,('Omni Air International','OY','OAE')
,('One Two Go Airlines',NULL,'OTG')
,('Onur Air','8Q','OHY')
,('Orenburg Airlines','R2','ORB')
,('Orient Thai Airlines','OX','OEA')
,('Origin Pacific Airways','QO','OGN')
,('Ostfriesische Lufttransport','OL','OLT')
,('Overland Airways','OJ','OLA')
,('Ozjet Airlines','O7','OZJ')
,('PAN Air','PV','PNR')
,('PB Air','9Q','PBA')
,('PLUNA','PU','PUA')
,('PMTair','U4','PMT')
,('Jetstar Pacific','BL','PIC')
,('Pacific Coastal Airline','8P','PCO')
,('Pacific East Asia Cargo Airlines','Q8','PEC')
,('Pacific Island Aviation',NULL,'PSA')
,('Pacific Wings','LW','NMI')
,('Pakistan International Airlines','PK','PIA')
,('Paramount Airways','I7','PMW')
,('Passaredo Transportes Aereos',NULL,'PTB')
,('Pegasus Airlines','PC','PGT')
,('Peninsula Airways','KS','PEN')
,('Philippine Airlines','PR','PAL')
,('Piedmont Airlines (1948-1989)','PI','PDT')
,('Pinnacle Airlines','9E','FLG')
,('Polet',NULL,'POT')
,('Polynesian Airlines','PH','PAO')
,('Porter Airlines','PD','POE')
,('Portugalia','NI','PGA')
,('Potomac Air','BK','PDC')
,('Precision Air','PW','PRF')
,('Privatair',NULL,'PTI')
,('Proflight Commuter Services','P0',NULL)
,('Qantas','QF','QFA')
,('Qatar Airways','QR','QTR')
,('RACSA','R6',NULL)
,('Kinloss Flying Training Unit',NULL,'KIN')
,('Regional Airlines','FN',NULL)
,('Regional Express','ZL','RXA')
,('Republic Airlines','RW','RPA')
,('Republic Express Airlines','RH','RPH')
,('Rossiya','R4',NULL)
,('Air Rarotonga','GZ','RAR')
,('Royal Air Maroc','AT','RAM')
,('Royal Brunei Airlines','BI','RBA')
,('Royal Jordanian','RJ','RJA')
,('Royal Nepal Airlines','RA','RNA')
,('Royal Phnom Penh Airways',NULL,'PPW')
,('Rusline',NULL,'RLU')
,('Rwandair Express','WB','RWD')
,('Ryan Air Services',NULL,'RYA')
,('Ryan International Airlines','RD','RYN')
,('Ryanair','FR','RYR')
,('Régional','YS','RAE')
,('SATA International','S4','RZO')
,('South African Airways','SA','SAA')
,('Shaheen Air International','NL','SAI')
,('Scandinavian Airlines System','SK','SAS')
,('ScotAirways',NULL,'SAY')
,('S7 Airlines','S7','SBI')
,('Seaborne Airlines','BB','SBS')
,('Scenic Airlines',NULL,'SCE')
,('SriLankan Airlines','UL','ALK')
,('Sun Country Airlines','SY','SCX')
,('Southeast Air',NULL,'SEA')
,('Sky Express','G3','SEH')
,('Spicejet','SG','SEJ')
,('Star Flyer','7G','SFJ')
,('Skagway Air Service','N5','SGY')
,('Sahara Airlines',NULL,'SHD')
,('SATA Air Acores','SP','SAT')
,('Singapore Airlines','SQ','SIA')
,('Sibaviatrans','5M','SIB')
,('Skynet Airlines','SI','SIH')
,('Sriwijaya Air','SJ','SJY')
,('Sama Airlines','ZS','SMY')
,('Singapore Airlines Cargo','SQ','SQC');
REPLACE INTO airlines(name,iata_code,icao_code) VALUES
 ('Siem Reap Airways','FT','SRH')
,('South East Asian Airlines','DG','SRQ')
,('Skyservice Airlines','5G','SSV')
,('Servicios de Transportes A','FS','STU')
,('Sudan Airways','SD','SUD')
,('Saudi Arabian Airlines','SV','SVA')
,('Southwest Airlines','WN','SWA')
,('Southern Winds Airlines','A4','SWD')
,('Swiss International Air Lines','LX','SWR')
,('Swissair','SR','SWR')
,('Swiss European Air Lines',NULL,'SWU')
,('Swe Fly','WV','SWV')
,('SunExpress','XQ','SXS')
,('Syrian Arab Airlines','RB','SYR')
,('Skywalk Airlines','AL','SYX')
,('Shandong Airlines','SC','CDG')
,('SAS Braathens',NULL,'CNO')
,('Spring Airlines','9S','CQH')
,('Sichuan Airlines','3U','CSC')
,('Shanghai Airlines','FM','CSH')
,('Shenzhen Airlines','ZH','CSZ')
,('Sun D\'Or','7L','ERO')
,('SkyEurope','NE','ESK')
,('Sky Europe Airlines',NULL,'HSK')
,('Spanair','JK','JKK')
,('Spirit Airlines','NK','NKS')
,('SATENA','9R','NSE')
,('Skywest Airlines',NULL,'OZW')
,('Santa Barbara Airlines','S3','BBR')
,('Sky Airline','H2','SKU')
,('SkyWest','OO','SKW')
,('Skyways Express','JZ','SKX')
,('Skymark Airlines','BC','SKY')
,('SilkAir','MI','SLK')
,('Surinam Airways','PY','SLM')
,('Sterling Airlines','NB','SNB')
,('Skynet Asia Airways','6J','SNJ')
,('Solomon Airlines','IE','SOL')
,('Southern Airways',NULL,'SOU')
,('Saratov Aviation Division','6W','SOV')
,('Sat Airlines','HZ','SOZ')
,('South Pacific Island Airways',NULL,'SPI')
,('Shuttle America','S5','TCF')
,('Scat Air','DV','VSV')
,('TAME','EQ','TAE')
,('TAM Brazilian Airlines','JJ','TAM')
,('TAP Portugal','TP','TAP')
,('Tunisair','TU','TAR')
,('Thai Air Cargo','T2','TCG')
,('Thomas Cook Airlines','FQ','TCW')
,('Thomas Cook Airlines','MT','TCX')
,('Trigana Air Service',NULL,'TGN')
,('Tiger Airways','TR','TGW')
,('Tiger Airways Australia','TT','TGW')
,('Thai Airways International','TG','THA')
,('Turk Hava Kurumu Hava Taksi Isletmesi',NULL,'THK')
,('Thai AirAsia','FD','AIQ')
,('Turkish Airlines','TK','THY')
,('Tajikistan International Airlines',NULL,'TIL')
,('Twin Jet','T7','TJT')
,('Translift Airways',NULL,'TLA')
,('Trans Mediterranean Airlines','TL','TMA')
,('Tiara Air','3P','TNM')
,('Thomsonfly','BY','TOM')
,('Tropic Air','PM','TOS')
,('TAMPA','QT','TPA')
,('TransAsia Airways','GE','TNA')
,('Transavia Holland','HV','TRA')
,('TACV','VR','TCV')
,('Transwest Air','9T','ABS')
,('Transaero Airlines','UN','TSO')
,('Turkmenistan Airlines','T5','TUA')
,('Tuninter','UG','TUI')
,('Travel Service','QS','TVS')
,('TUIfly Nordic','6B','BLX')
,('TAAG Angola Airlines','DT','DTA')
,('Turkish Air Force',NULL,'HVK')
,('TAM Mercosur','PZ','LAP')
,('Trans States Airlines','AX','LOF')
,('Tarom','RO','ROT')
,('Turan Air','3T','URN')
,('TRIP Linhas A','8R','TIB')
,('USA3000 Airlines','U5','GWY')
,('United Airlines','UA','UAL')
,('United Air Charters',NULL,'UAC')
,('Ural Airlines','U6','SVR')
,('UM Airlines','UF','UKM')
,('US Airways','US','USA')
,('US Helicopter',NULL,'USH')
,('UTair Aviation','UT','UTA')
,('United States Air Force',NULL,'AIO')
,('Uzbekistan Airways','HY','UZB')
,('Ukraine International Airlines','PS','AUI')
,('US Helicopter Corporation','UH',NULL)
,('Valuair','VF','VLU')
,('Vasco Air',NULL,'VFC')
,('Vietnam Airlines','VN','HVN')
,('VIM Airlines','NN','MOV')
,('Volaris','Y4','VOI')
,('Volga-Dnepr Airlines','VI','VDA');
REPLACE INTO airlines(name,iata_code,icao_code) VALUES
 ('Virgin America','VX','VRD')
,('Virgin Express','TV','VEX')
,('Virgin Nigeria Airways','VK','VGN')
,('Virgin Atlantic Airways','VS','VIR')
,('Viva Macau','ZG','VVM')
,('Volare Airlines','VE','VLE')
,('Vueling Airlines','VY','VLG')
,('Vladivostok Air','XF','VLK')
,('Varig Log','LC','VLO')
,('Virgin Australia','VA','VOZ')
,('VRG Linhas Aereas','RG','VRN')
,('VASP','VP','VSP')
,('VLM Airlines','VG','VLM')
,('Wayraper','7W',NULL)
,('WebJet Linhas A','WJ','WEB')
,('Welcome Air','2W','WLC')
,('West Coast Air','8O',NULL)
,('WestJet','WS','WJA')
,('Western Airlines','WA','WAL')
,('Widerøe','WF','WIF')
,('Wind Jet','IV','JET')
,('Wings Air','IW','WON')
,('Wizz Air','W6','WZZ')
,('Wizz Air Hungary','8Z','WVL')
,('World Airways','WO','WOA')
,('XL Airways France','SE','SEU')
,('Xiamen Airlines','MF','CXA')
,('Yamal Airlines','YL','LLM')
,('Yemenia','IY','IYE')
,('Yuzhmashavia',NULL,'UMK')
,('Zanair',NULL,'TAN')
,('Zoom Airlines','Z4','OOM')
,('Tyrolean Airways',NULL,'TYR')
,('Maldivian Air Taxi','8Q',NULL)
,('Sky Express','XW','SXR')
,('Royal Air Cambodge','VJ','RAC')
,('Air Mandalay','6T',NULL)
,('Air Busan','BX','ABL')
,('Globus','GH','GLP')
,('Air Kazakhstan','9Y','KZK')
,('Japan Air System','JD','JAS')
,('EasyJet (DS)','DS',NULL)
,('Star Peru (2I)','2I',NULL)
,('Carnival Air Lines','KW',NULL)
,('United Airways','4H','UBD')
,('Fly540','5H','FFV')
,('Transavia France','TO','TVF')
,('Island Air (WP)','WP','MKU')
,('Uni Air','B7','UIA')
,('Gomelavia','YD',NULL)
,('Red Wings','WZ','RWZ')
,('TUIfly (X3)','11',NULL)
,('Felix Airways','FU','FXX')
,('Kostromskie avialinii','K1','KOQ')
,('Greenfly','XX','GFY')
,('Tajik Air','7J',NULL)
,('Air Mozambique','TM',NULL)
,('ELK Airways','--','ELK')
,('Gabon Airlines','GY','GBK')
,('MCA Airlines',NULL,'MCA')
,('Maldivo Airlines','ML','MAV')
,('Virgin Pacific','VH','VNP')
,('Zest Air','Z2',NULL)
,('Yangon Airways','HK',NULL)
,('Eastar Jet','ZE','ESR')
,('Jin Air','LJ','JNA')
,('Wataniya Airways',NULL,'KW1')
,('Air Arabia Maroc','3O',NULL)
,('Baltic Air lines','B1','BA1')
,('Ciel Canadien','YC','YCC')
,('Canadian National Airways','CN','YCP')
,('Epic Holiday','FA','4AA')
,('Indochina Airlines',NULL,'AXC')
,('Air Comet Chile','3I',NULL)
,('German Air Force - FLB',NULL,'FLB')
,('Line Blue','L8','LBL')
,('FlyLAL Charters',NULL,'LLC')
,('Salzburg arrows','SZ',NULL)
,('Texas Wings','TQ','TXW')
,('Dennis Sky','DH','DSY')
,('Zz','ZZ',NULL)
,('Atifly','A1','A1F')
,('Aerolineas heredas santa maria',NULL,'SZB')
,('Ciao Air','99',NULL)
,('Jc royal.britannica',NULL,'JRB')
,('Pal airlines','5P',NULL)
,('CanXpress','C1','CA1')
,('Danube Wings (V5)','V5',NULL)
,('Sharp Airlines','SH','SHA')
,('CanXplorer','C2','CAP')
,('Click (Mexicana)','QA',NULL)
,('World Experience Airline','W1','WE1')
,('ALAK','J4',NULL)
,('Air Choice One','3E',NULL)
,('Tianjin Airlines',NULL,'GCR')
,('China United','KN',NULL)
,('Locair','ZQ','LOC')
,('Safi Airlines','4Q',NULL)
,('SeaPort Airlines','K5','SQH')
,('Salmon Air','S6',NULL);
REPLACE INTO airlines(name,iata_code,icao_code) VALUES
 ('Bobb Air Freight','1',NULL)
,('Star1 Airlines','V9','HCW')
,('Pelita','D 6.00',NULL)
,('Alaska Seaplane Service','J5',NULL)
,('Enerjet',NULL,'ENJ')
,('MexicanaLink','I6','MXI')
,('Island Spirit','IP','ISX')
,('TACA Peru','T0',NULL)
,('Orbest',NULL,'OBS')
,('Southern Air Charter',NULL,'SOA')
,('SVG Air',NULL,'SVG')
,('Air Century',NULL,'CEY')
,('Pan Am World Airways Dominicana','7Q',NULL)
,('Primera Air','PF',NULL)
,('Air Antilles Express','3S',NULL)
,('Sol Lineas Aereas',NULL,'OLS')
,('Regional Paraguaya','P7','REP')
,('VIP Ecuador','V6',NULL)
,('Transportes Aereos Cielos Andinos',NULL,'NDN')
,('Peruvian Airlines','P9',NULL)
,('EasyFly',NULL,'EFY')
,('Polar Airlines','ЯП',NULL)
,('Catovair','OC',NULL)
,('Andalus Lineas Aereas',NULL,'ANU')
,('Air 26',NULL,'DCD')
,('Mauritania Airways',NULL,'MTW')
,('CEIBA Intercontinental',NULL,'CEL')
,('Halcyonair','7Z',NULL)
,('Business Aviation','4P',NULL)
,('Compagnie Africaine d\\\\\'Aviation','E9',NULL)
,('Zambia Skyways','K8',NULL)
,('AlMasria Universal Airlines','UJ','LMU')
,('EgyptAir Express',NULL,'MSE')
,('SmartLynx Airlines','6Y',NULL)
,('Air Italy Egypt',NULL,'EUD')
,('KoralBlue Airlines','K7','KBR')
,('Wind Rose Aviation',NULL,'WRC')
,('Elysian Airlines','E4','GIE')
,('Sevenair',NULL,'SEN')
,('Hellenic Imperial Airways','HT','IMP')
,('Amsterdam Airlines','WD','AAN')
,('Arik Niger','Q9','NAK')
,('Dana Air','DA',NULL)
,('STP Airways','8F','STP')
,('Med Airways','7Y',NULL)
,('Skyjet Airlines','UQ','SJU')
,('Air Volga','G6',NULL)
,('Transavia Denmark',NULL,'TDK')
,('Royal Falcon','RL','RFJ')
,('Euroline','4L','MJX')
,('Turkuaz Airlines',NULL,'TRK')
,('Athens Airways','ZF',NULL)
,('Viking Hellas','VQ','VKH')
,('Norlandair',NULL,'FNA')
,('Flugfelag Vestmannaeyja',NULL,'FVM')
,('Starline.kz','DZ',NULL)
,('Lugansk Airlines','L7',NULL)
,('Gryphon Airlines','6P',NULL)
,('Gadair European Airlines','GP','GDR')
,('Spirit of Manila Airlines','SM','MNP')
,('Chongqing Airlines','OQ','CQN')
,('Grand China Air',NULL,'GDC')
,('West Air China','PN','CHB')
,('QatXpress','C3','QAX')
,('OneChina','1C','1CH')
,('NordStar Airlines','Y7',NULL)
,('Joy Air','JR','JOY')
,('Air India Regional','CD',NULL)
,('MDLR Airlines','9H',NULL)
,('Jagson Airlines',NULL,'JGN')
,('Maldivian','Q2',NULL)
,('Xpressair','XN',NULL)
,('Strategic Airlines','VC',NULL)
,('Fars Air Qeshm',NULL,'QFZ')
,('Eastok Avia',NULL,'EAA')
,('Jupiter Airlines',NULL,'JPU')
,('Vision Air International',NULL,'VIS')
,('Al-Naser Airlines','NA',NULL)
,('Fuji Dream Airlines','JH',NULL)
,('Korea Express Air',NULL,'KEA')
,('Eznis Airways',NULL,'EZA')
,('Pacific Flier',NULL,'PFL')
,('Syrian Pearl Airlines',NULL,'PSB')
,('SGA Airlines','5E',NULL)
,('Air2there','F8',NULL)
,('Avianova (Russia)','AO',NULL)
,('Parmiss Airlines (IPV)','PA','IPV')
,('EuropeSky','ES','EUV')
,('BRAZIL AIR','GB','BZE')
,('Homer Air','MR','OME')
,('U.S. Air','-+','--+')
,('Jayrow','\\\\\'','\\\\\'\\\\')
,('Wilderness Air',';;',NULL)
,('Whitaker Air','^^',NULL)
,('PanAm World Airways','WQ','PQW')
,('Virginwings','YY','VWA')
,('KSY','KY','KSY')
,('Buquebus Líneas Aéreas','BQ','BQB')
,('SOCHI AIR','CQ','KOL')
,('Wizz Air Ukraine','WU','WAU');
REPLACE INTO airlines(name,iata_code,icao_code) VALUES
 ('88','47','VVN')
,('LCM AIRLINES','LQ','LMM')
,('Cambodia Angkor Air (K6)','K6',NULL)
,('Royal European Airlines','69',NULL)
,('Tom\\\\\'s & co airliners','&T','T&O')
,('Azul','AD','AZU')
,('LSM Airlines','PQ','LOO')
,('Zapolyarie Airlines',NULL,'PZY')
,('Finlandian',NULL,'FN1')
,('LionXpress','C4','LIX')
,('Genesis','GK',NULL)
,('Congo Express','XZ',NULL)
,('Fly Dubai','FZ','FDB')
,('Domenican Airlines','D 1.00','MDO')
,('ConneX European Airline',NULL,'2CO')
,('Aereonautica militare','JY','AXZ')
,('Kal Star Aviation',NULL,'KLS')
,('LSM AIRLINES','YZ','YZZ')
,('UTair-Express','UR',NULL)
,('Huaxia','G5',NULL)
,('Zabaykalskii Airlines','ZP','ZZZ')
,('CBM America',NULL,'XBM')
,('Marysya Airlines','M4','1QA')
,('N1','N1',NULL)
,('Airlink (SAA)','4Z',NULL)
,('Westfalia Express VA',NULL,'WFX')
,('JobAir','3B',NULL)
,('Black Stallion Airways','BZ','BSA')
,('German International Air Lines','GM','GER')
,('TrasBrasil','TB','TBZ')
,('TransBrasil Airlines','TH','THS')
,('China SSS','9C',NULL)
,('AIR INDOCHINE',NULL,'IIA')
,('Happy Air',NULL,'HPY')
,('Solar Air',NULL,'SRB')
,('Air Mekong','P8','MKG')
,('Harbour Air (Priv)','H3',NULL)
,('Air Hamburg (AHO)','HH','AHO')
,('ZABAIKAL AIRLINES','Z6','ZTT')
,('TransHolding','TI','THI')
,('SUR Lineas Aereas',NULL,'SZZ')
,('Aerolineas Africanas',NULL,'AA1')
,('Yeti Airways','YT',NULL)
,('Yellowstone Club Private Shuttle','Y1',NULL)
,('Caucasus Airlines','NS',NULL)
,('Serbian Airlines','S1','SA1')
,('Windward Islands Airways','WM',NULL)
,('TransHolding System','YO','TYS')
,('CCML Airlines','CB','CCC')
,('Small Planet Airlines',NULL,'ELC')
,('Fly Brasil','F1','FBL')
,('CB Airways UK ( Interliging Flights )','1F','CIF')
,('Fly Colombia ( Interliging Flights )','3F','3FF')
,('Trans Pas Air','T6','TP6')
,('KMV','МИ',NULL)
,('Himalayan Airlines','HC','HYM')
,('Indya Airline Group','G1','IG1')
,('Sunwing','WG',NULL)
,('Turkish Wings Domestic',NULL,'TWD')
,('Japan Regio','ZX','ZXY')
,('OCEAN AIR CARGO',NULL,'IXO')
,('Norte Lineas Aereas','N0',NULL)
,('Austral Brasil','W7',NULL)
,('PEGASUS AIRLINES-','H9',NULL)
,('Nihon.jet connect',NULL,'NX1')
,('Camair-co','QC',NULL)
,('Sky Regional','RS','SKV')
,('LSM International','II','UWW')
,('Baikotovitchestrian Airlines','BU','BUU')
,('Luchsh Airlines','L4','LJJ')
,('ENTERair',NULL,'QQQ')
,('Air Cargo Germany','6U',NULL)
,('Mongolian International Air Lines','7M','ZTF')
,('Tway Airlines','TW','TWB')
,('Papillon Grand Canyon Helicopters','HI',NULL)
,('Jusur airways','JX','JSR')
,('NEXT Brasil','XB','NXB')
,('AeroWorld','W4','WER')
,('GNB Linhas Aereas','GN',NULL)
,('Usa Sky Cargo','E1','ES2')
,('Hankook Airline','HN','HNX')
,('REDjet','Z7',NULL)
,('Red Jet Andes','PT',NULL)
,('Red Jet Canada','QY',NULL)
,('Sprintair',NULL,'SRN')
,('Red Jet Mexico','4X',NULL)
,('Marusya Airways','Y8','MRS')
,('Era Alaska','7H','ERR')
,('AirRussia','R8','RRJ')
,('Hankook Air US','H1','HA1')
,('Carpatair Flight Training',NULL,'SMW')
,('I-Fly','H5','RSY')
,('Whitejets',NULL,'WTJ')
,('VickJet','KT','VKJ')
,('BVI Airways','XV',NULL)
,('Hamburg Airways',NULL,'HAY')
,('Salsa d\\\\\'Haiti','SO','SLC')
,('Zambezi Airlines (ZMA)','ZJ',NULL)
,('Kan Air',NULL,'KND')
,('Air Cudlua',NULL,'CUD');
REPLACE INTO airlines(name,iata_code,icao_code) VALUES
 ('Polet Airlines (Priv)','YQ',NULL)
,('Air Explore',NULL,'AXE')
,('12 North','12','N12')
,('Holidays Czech Airlines',NULL,'HCC')
,('Comtel Air',NULL,'COE')
,('Mint Airways',NULL,'MIC')
,('Orbit Airlines',NULL,'OBT')
,('Air Bucharest',NULL,'BUR')
,('AlbaStar',NULL,'LAV')
,('Mauritania Airlines International','L6','MAI')
,('MAT Airways','6F','MKD')
,('Asian Wings Airways','AW','AWM')
,('Air Arabia Egypt','E5','RBG')
,('Eagles Airlines',NULL,'EGS')
,('YES Airways',NULL,'YEP')
,('Alitalia Cityliner','CT',NULL)
,('Direct Aero Services',NULL,'DSV')
,('Medallion Air',NULL,'MDP')
,('Orchid Airlines','OI','ORC')
,('Asia Wings','Y5','AWA')
,('Georgian International Airlines',NULL,'GNN')
,('Air Batumi',NULL,'BTM')
,('Skywest Australia','XR',NULL)
,('Nile Air','NP','NIA')
,('Feeder Airlines',NULL,'FDD')
,('Senegal Airlines','DN','SGG')
,('Fly 6ix','6I',NULL)
,('Starbow Airlines','S9',NULL)
,('Copenhagen Express','0X','CX0')
,('BusinessAir','8B','BCC')
,('SENIC AIRLINES','YR',NULL)
,('XOJET',NULL,'XOJ')
,('Sky Wing Pacific','C7','CR7')
,('Bateleur Air',NULL,'BEU')
,('Air Indus','PP','AI0')
,('Orbit International Airlines',NULL,'OAI')
,('Orbit Regional Airlines',NULL,'OAR')
,('Orbit Atlantic Airways',NULL,'OAN')
,('Volotea',NULL,'VOO')
,('Peach Aviation','MM',NULL)
,('Helitt Líneas Aéreas',NULL,'HTH')
,('Russia State Transport',NULL,'RSD')
,('Malaysia Wings',NULL,'MWI')
,('Aviabus','U1','ABI')
,('Michael Airlines','DF','MJG')
,('Korongo Airlines','ZC','KGO')
,('Indonesia Sky','I5','IDS')
,('Aws express','B0','666')
,('Southjet','76','SJS')
,('Southjet connect','77','ZCS')
,('Southjet cargo','78','XAN')
,('Iberia Express','I2','IBS')
,('Interjet (ABC Aerolineas)','4O',NULL)
,('AirOnix','OG',NULL)
,('Nordic Global Airlines','NJ','NGB')
,('Scoot','TZ','SCO')
,('Hi Fly (5K)','5K',NULL)
,('China Northwest Airlines (WH)','WH',NULL)
,('Zenith International Airline','ZN','ZNA')
,('Orbit Airlines Azerbaijan','O1','OAB')
,('Air Alps Aviation (A6)','A6',NULL)
,('Flying kangaroo Airline',NULL,'FKA')
,('RusJet',NULL,'RSJ')
,('VietJet Air',NULL,'VJC')
,('Patriot Airways','P4',NULL)
,('Vision Airlines (V2)','V2','RBY')
,('BQB Lineas Aereas','5Q',NULL)
,('AirAsia Japan',NULL,'WAJ')
,('Yellowtail','YE','YEL')
,('Royal Airways','KG','RAW')
,('FlyHigh Airlines Ireland (FH)','FH','FHI')
,('Executive AirShare',NULL,'XSR')
,('Hebei Airlines',NULL,'HBH')
,('Air KBZ',NULL,'KBZ')
,('Aero VIP (2D)','D 2.00',NULL)
,('Yangon Airways Ltd.','YH',NULL)
,('T.J. Air','TJ','TJA')
,('SkyWork Airlines','SX',NULL)
,('Maastricht Airlines','W2',NULL)
,('Euro Jet','24',NULL)
,('Ukraine Atlantic',NULL,'UAT')
,('Nesma Airlines',NULL,'NMA')
,('East Horizon',NULL,'EHN')
,('Air Majoro',NULL,'MJP')
,('Rotana Jet',NULL,'RJD')
,('SOCHI AIR CHATER','Q3','QER')
,('Denim Air','J7',NULL)
,('Malindo Air','OD','MXD')
,('Hermes Airlines',NULL,'HRM')
,('Flightlink Tanzania','Z9',NULL)
,('IzAvia','I8',NULL)
,('Катэкавиа',NULL,'КТК')
,('Псковавиа',NULL,'PKV')
,('Maryland Air','M1','M1F')
,('Insel Air (7I/INC) (Priv)','7I',NULL)
,('VivaColombia','5Z','VVC')
,('Flybe Finland Oy',NULL,'FCM')
,('Bingo Airways',NULL,'BGY')
,('Bluebird Airways (BZ)',NULL,'BBG')
,('Apache Air','ZM','IWA');
REPLACE INTO airlines(name,iata_code,icao_code) VALUES
 ('MHS Aviation GmbH','M2',NULL)
,('Jettor Airlines','NR','JTO')
,('Flyme (VP)',NULL,'VQI')
,('Thai Lion Air','SL',NULL)
,('Golden Myanmar Airlines',NULL,'GMR')
,('Canaryfly',NULL,'CNF')
,('Sunrise Airways',NULL,'KSZ')
,('National Air Cargo','N8','NCR')
,('Eastern Atlantic Virtual Airlines','13','EAV')
,('Citilink Indonesia','QG',NULL)
,('Transair',NULL,'TTZ')
,('Comfort Express Virtual Charters Albany',NULL,'EVC')
,('Comfort Express Virtual Charters',NULL,'CEO')
,('FLYJET',NULL,'FYJ')
,('Snowbird Airlines','S8','SBD')
,('Russkie Krylya',NULL,'KRY')
,('Kharkiv Airlines','KH','KHK')
,('XAIR USA','XA','XAU')
,('Air Costa','LB',NULL)
,('Simrik Airlines',NULL,'RMK')
,('XPTO','XP','XPT')
,('Royal Flight',NULL,'DME')
,('BBN-Airways',NULL,'EGH')
,('Tomsk-Avia',NULL,'TKS')
,('Malawian Airlines','3W',NULL)
,('Yeti Airlines',NULL,'NYT')
,('Avilu','..','...')
,('Air Serbia','JU','ASL')
,('Skyline Ulasim Ticaret A.S.',NULL,'KCU')
,('Air Lituanica','LT','LTU')
,('Envoy Air',NULL,'ENY')
,('CARICOM AIRWAYS (BARBADOS) INC.',NULL,'CCB')
,('Rainbow Air (RAI)','RN','RAB')
,('Rainbow Air Canada','RY','RAY')
,('Rainbow Air Polynesia','RX','RPO')
,('Rainbow Air Euro','RU','RUE')
,('Rainbow Air US','RM','RNY')
,('Transilvania',NULL,'TNS')
,('Dobrolet','QD','DOB')
,('Spike Airlines','S0','SAL')
,('Grand Cru Airlines',NULL,'GCA')
,('Go2Sky',NULL,'RLX')
,('All Argentina','L1','AL1')
,('All America','A2','AL2')
,('All Asia','L9','AL3')
,('All Africa','9A','99F')
,('Regionalia México','N4','J88')
,('All Europe','N9','N99')
,('All Spain','N7','N77')
,('Regional Air Iceland','9N','N78')
,('Voestar','8K','K88')
,('All Colombia','7O','7KK')
,('Regionalia Uruguay','2X','2K2')
,('Regionalia Venezuela','9X','9XX')
,('Regionalia Chile','9J','CR1')
,('Vuela Cuba','6C','6CC')
,('All Australia','88','8K8')
,('Fly Europa','ER','RWW')
,('FlyPortugal','PO','FPT')
,('Spring Airlines Japan','IJ','SJO')
,('Dense Airways','KP','DWA')
,('Dense Connection','KZ','DC2')
,('Vuola Italia','4S','VI4')
,('Jet Suite',NULL,'RSP')
,('Fly Jamaica Airways',NULL,'FJM')
,('Island Express Air','1X',NULL)
,('All Argentina Express','Z0','Z9H')
,('Thai Smile Airways','WE',NULL)
,('International AirLink','I4',NULL)
,('Real Tonga','RT',NULL)
,('All America AR','2R','M7A')
,('All America CL','1R','R1R')
,('SOCHI AIR EXPRESS','Q4','SAE')
,('All America BR','1Y','A9B')
,('Volotea Costa Rica','9V','VC9')
,('Fly Romania','X5','OTJ')
,('Eagle Atlantic Airlines','E2',NULL)
,('Fly Africa Zimbabwe',NULL,'FZW')
,('San Dima Air',NULL,'SDI')
,('All America CO','0Y','7ZC')
,('All America MX','0M','0MM')
,('FOX Linhas Aereas','FX','FOX')
,('Air Kenya (Priv)','QP',NULL)
,('Via Conectia Airlines','6V','CZV')
,('Hebradran Air Services',NULL,'HBR')
,('Pobeda',NULL,'PBD')
,('City Airways','E8','GTA')
,('Norwegian Long Haul AS','DU','NLH')
,('BA101',NULL,'710')
,('TransNusa Air','M8','TNU')
,('Tomp Airlines','ZT','T9P')
,('Fuzhou Airlines',NULL,'FZA')
,('Sky Angkor Airlines (ZA)',NULL,'SWM')
,('OneJet','J1',NULL)
,('Global Airlines','0G','GA0')
,('Mann Yadanarpon Airlines',NULL,'MYP')
,('Air Vistara','UK','VTI')
,('TransRussiaAirlines','1E','RGG')
,('Severstal Air Company','D 2.00',NULL)
,('REXAIR VIRTUEL','RR','RXR');
REPLACE INTO airlines(name,iata_code,icao_code) VALUES
 ('WestJet Encore','WR','WEN')
,('Air Pegasus','OP','PPL')
,('International Europe','9I','INE')
,('Sky Regional Airlines',NULL,'SKV')
,('V Air','ZV','VAX')
,('Cello Aviation',NULL,'CLJ')
,('Pouya Air',NULL,'PYA')
,('Boutique Air (Priv)','4B','BTQ')
,('FlyEgypt',NULL,'FEG')
,('VOLOTEA Airways','V7','VOE')
,('INAVIA Internacional','Z5','IIR')
,('Liberty Airways','LE','LTY')
,('Аэросервис','АЯ',NULL)
,('Aeronautica Militare',NULL,'IAM')
,('Bassaka airlines','5B','BSX')
,('Jetstar Japan',NULL,'JJP')
,('SkyBahamas Airlines','Q7',NULL)
,('UVT Aero','UW',NULL)
,('First Flying',NULL,'DAK')
,('Silver Airways (3M)','3M',NULL)
,('AtlasGlobal Ukraine',NULL,'UJX')
,('Boliviana de Aviacion (OB)',NULL,'BOV')
,('US-Bangla Airlines',NULL,'UBG')
,('Norwegian Air International (D8)',NULL,'IBK')
,('ATA Airlines (Iran)','I3',NULL)
,('VIA Líneas Aéreas','V1','VIA')
,('GermanXL','GX','GXG')
,('Alghanim',NULL,'KYA')
,('Indonesa Air Aisa X',NULL,'IDX')
,('Fly France','FF','FRF')
,('Jota Aviation',NULL,'ENZ')
,('Europe Jet','EX','EU9')
,('COBALT',NULL,'FCB')
,('Southern Airways Express',NULL,'LTD')
,('Orenburzhie',NULL,'ORG')
,('World Scale Airlines','W3','WSS')
,('All America US','AG','SSA')
,('University of Birmingham Air Squadron (RAF)',NULL,'UAY')
,('Choice Airways',NULL,'CSX')
,('Aruba Airlines',NULL,'ARU')
,('BudgetAir','1K','BG1')
,('Dynamic Airways',NULL,'DYA')
,('Fly One','F5','FI5')
,('Nordica','EE',NULL)
,('Tez Jet Airlines',NULL,'TEZ')
,('Kush Air',NULL,'KUH')
,('ViaAir',NULL,'SRY')
,('All America BOPY','0P','PYB')
,('Thai Vietjet Air',NULL,'TVJ')
,('GX Airlines',NULL,'CBG')
,('Jetgo Australia','JG',NULL)
,('Air Carnival','2S',NULL)
,('Svyaz Rossiya','7R','SJM');
